name: CodeQuest Scoring System

on:
  schedule:
    - cron: "5 0 * * *"  # Runs daily at 12:05 AM
  workflow_dispatch:  # Allows manual triggering

jobs:
  scoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests pandas flake8

      - name: Fetch Submissions & Calculate Scores
       env:
  GITHUB_TOKEN: ${{ secrets.CODEQUEST_ACCESS_TOKEN }}

        run: python scripts/score_calculator.py

      - name: Commit and Push Score Updates
        run: |
          git config --global user.name "CodeQuestBot"
          git config --global user.email "bot@codequest.com"
          git add leaderboard.json
          git commit -m "Updated leaderboard"
          git push
