name: Auto Merge PRs
on:
  pull_request:
    types:
      - opened
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
